"use client"
import "@libs/globals.css"

import { NavBar } from "t4-navbar-react"

export const metadata = {
  title: 'Desir Designs',
  description: 'Generated by create next app',
}


export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body >
        <NavBar componentName="Larry" />
        {children}
      </body>
    </html>
  )
}
